export const GET_ALL_LISTINGS="GET_ALL_LISTINGS"


export const LOGIN_USER="LOGIN_USER"
export const CREATE_USER="CREATE_USER"
export const FORGET_PASSWORD="FORGET_PASSWORD"
export const VERIFY_CODE="VERIFY_CODE"
export const RESET_PASSWORD="RESET_PASSWORD";
export const GET_PROPERTY_FOR_RENT_LISTING="GET_PROPERTY_FOR_RENT_LISTING";
export const GET_PROPERTY_FOR_SELL_LISTING="GET_PROPERTY_FOR_SELL_LISTING";
export const GET_PROPERTY_FOR_LAND_LISTING="GET_PROPERTY_FOR_LAND_LISTING"
export const GET_PROPERTY_FOR_CAR_LISTING="GET_PROPERTY_FOR_CAR_LISTING"
export const GET_LISTING_BY_ID="GET_LISTING_BY_ID"
export const ADD_PROPERTY_FOR_RENT_LISTING="ADD_PROPERTY_FOR_RENT_LISTING"
export const GET_LOGGED_IN_USER="GET_LOGGED_IN_USER"
export const UPDATE_USER="UPDATE_USER"
export const CHANGE_PASSWORD="CHANGE_PASSWORD"
export const ADD_LISTING="ADD_LISTING";
export const GET_USER_BY_ID ="GET_USER_BY_ID";
export const ADD_TO_FAVOURITE="ADD_TO_FAVOURITE";
export const GET_LOGGED_USER_FAVOURITE="GET_LOGGED_USER_FAVOURITE"
export const GET_LOGGED_USER_LISTING="GET_LOGGED_USER_LISTING"
export const DELETE_FAVOURITE="DELETE_FAVOURITE"

export const SEND_MESSAGE="SEND_MESSAGE";
export const RECEIVE_MESSAGE="RECEIVE_MESSAGE";
export const GET_ALL_MESSAGES="GET_ALL_MESSAGES";
export const GET_USERS_FOR_SIDEBAR="GET_USERS_FOR_SIDEBAR";
export const UPDATE_FCM_TOKEN="UPDATE_FCM_TOKEN";
export const SET_SELECTED_USER="SET_SELECTED_USER";
export const ADD_MESSAGE_REAL_TIME="ADD_MESSAGE_REAL_TIME";
export const UPDATE_SIDEBAR_REAL_TIME="UPDATE_SIDEBAR_REAL_TIME";
export const GET_ALL_USERS="GET_ALL_USERS";




//admin

export const GET_ALL_USERS_FOR_ADMIN="GET_ALL_USERS_FOR_ADMIN";
export const ACCEPT_LISTING ="ACCEPT_LISTING"
export const REJECT_LISTING="REJECT_LISTING"




//category id

export const   CATEGORY_RENT_ID=`68168126919277fc38d33023`
export const   CATEGORY_SELL_ID=`681680fb919277fc38d33021`
export const   CATEGORY_LAND_ID=`68168137919277fc38d33025`
export const   CATEGORY_CAR_ID=`6816814c919277fc38d33027` 



